name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Generate release tag
        id: tag
        run: echo "release_tag=v$(date +'-%Y.%m.%d')" >> $GITHUB_OUTPUT
        # -${GITHUB_SHA::7}

      - name: Build binaries
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/matrix-linux-amd64 ./cmd/main.go
          GOOS=linux GOARCH=arm64 go build -o build/matrix-linux-arm64 ./cmd/main.go
          GOOS=windows GOARCH=amd64 go build -o build/matrix-windows-amd64 ./cmd/main.go
          GOOS=windows GOARCH=arm64 go build -o build/matrix-windows-arm64 ./cmd/main.go
          GOOS=darwin GOARCH=amd64 go build -o build/matrix-darwin-amd64 ./cmd/main.go
          GOOS=darwin GOARCH=arm64 go build -o build/matrix-darwin-arm64 ./cmd/main.go

      - name: Generate checksums
        run: |
          cd build
          sha256sum matrix-linux-amd64 matrix-linux-arm64 matrix-windows-amd64 matrix-windows-arm64 matrix-darwin-amd64 matrix-darwin-arm64 > checksums.txt

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.tag.outputs.release_tag }}
        run: |
          # Create release notes from git log
          git fetch --prune --unshallow
          RELEASE_NOTES=$(git log -1 --pretty=format:%b)
          if [ -z "$RELEASE_NOTES" ]; then
            RELEASE_NOTES="Release $TAG"
          fi
          
          # Create release and upload assets
          gh release create "$TAG" \
            --title "Release $TAG" \
            --notes "$RELEASE_NOTES" \
            build/matrix-linux-amd64 \
            build/matrix-linux-arm64 \
            build/matrix-windows-amd64 \
            build/matrix-windows-arm64 \
            build/matrix-darwin-amd64 \
            build/matrix-darwin-arm64 \
            build/checksums.txt
